### ISSUE TITLE
Add this list to the list of awesome lists (sindresorhus/awesome)

### ISSUE THREAD

**Issue by mesaugat** [techgaun/awesome-programming-presentations#11]
Here is what we need to do: https://github.com/sindresorhus/awesome/blob/master/create-list.md

This list should probably go into the miscellaneous section: https://github.com/sindresorhus/awesome#miscellaneous

**Comment by techgaun** [comment]
would be great to do so. I just don't have bandwidth to do so right now. If you would like to help, I can review and put the PR in. Otherwise, I will keep this in my todo for next weekend.

**Comment by mesaugat** [comment]
Here it is #13

**Comment by techgaun** [comment]
@mesaugat thanks so much. I will try to do a PR to awesome around next week (anything I'm missing for this to be compliant?) but if you wanna do that, feel free to :)

**Comment by mesaugat** [comment]
They recommend a Creative Commons (CC) license. The only thing I am skeptic about is that they already have a similar list i.e. awesome-talks
